package main

var tb byte = byte('b')
var ti byte = byte('i')
var tf byte = byte('f')
var ts byte = byte('s')
var tl byte = byte('l')
var tm byte = byte('m')
var tn byte = byte('n')
var crlf []byte = []byte("\\r\\n")
var delimit []byte = []byte("\r\n")
var delimit2 []byte = []byte("\t\n")
var blank []byte = []byte("")
var comma []byte = []byte(",")
var questionMark []byte = []byte("?")
var partitionMark []byte = []byte("|")
var delimiter []byte = []byte(":")
var equal []byte = []byte("=")
var greater []byte = []byte(">")
var greaterEqual []byte = []byte(">=")
var less []byte = []byte("<")
var lessEqual []byte = []byte("<=")
var zero []byte = []byte("0")
var one []byte = []byte("1")
var cindex []byte = []byte("index")
